title: Schwellenangst
subtitle: (n.) Fear of crossing a threshold to embark on something new  
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my homepage, a place where you can find information about me, my work, my hobbies, and maybe even learn a thing or two.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about
    - text: Blog
      url: /blog
    - text: Gallery
      url: /gallery
    - text: Shop
      url : /shop
    - text: Contact Me
      url : /contact
    - text: Styleguide
      url: /styleguide
    - text: Get Started
      url: /get-started

# Edit these details

author_logo: profile.png
author: Alexander Bogdan
author_bio: I'm currently a Lead Solution Engineer at Salesforce. Prior to that, I worked in the financial services sector designing algorithms for 
            predicting movements in foreign exchange and equities markets. I continue to conduct this research in my spare time, in addition to other tech-related 
            pursuits like building this website and tinkering with Raspberry Pis!
author_email: "alexander.bogdan.io@gmail.com"
author_location: United States of America
author_website_url: "https://arbogdan.github.io"
typewrite-text: Welcome to my homepage. Click around to learn more about me, what I do, and how we can be awesome together!

author_work_experiences:
            - company_name: Salesforce
              company_logo: salesforce_logo.png
              company_url: https://salesforce.com
              designation: Lead Solution Engineer
              description: Design dashboards that leverage machine learning & AI to optimize client KPIs and streamline data-driven value generation
              visibility: true
            - company_name: MassMutual
              company_logo: massmutual_logo.jpeg
              company_url: https://massmutual.com
              designation: Data Scientist
              description: Developed algorithms to predict movements in equities & foreign exchange markets
              visibility: true
            - company_name: University of Massachusetts Amherst
              company_logo: umass_seal_1500x1500px.jpg
              company_url: https://umass.edu
              designation: Research Fellow & Lecturer
              description: 
                - Collaborated with interdisciplinary team to develop models for predicting patients who would require antibiotic-resistant drug treatments
                - Contributed to clusterPower R package for simulating power calculations in cluster-randomized controlled trials (https://www.rdocumentation.org/packages/clusterPower/versions/0.6.111)
                - "Taught PUBHLTH 490ST: Storytelling through Data, Spring 2018" 
              visibility: true              
            - company_name: Cluj School of Publich Health
              company_logo: cluj_school_public_health_logo.svg
              company_url: https://publichealth.ro/
              designation: Fulbright Scholar & Visiting Lecturer
              description: 
                - Conducted research in women's health assessing associations between cervical cancer and arsenic contaminated groundwater
                - Taught introductory course in epidemiology to second year bachelor students 
              visibility: true

author_education_details:
              - college_logo: umass_seal_1500x1500px.jpg
                college_name: University of Massachusetts Amherst
                college_url: https://umass.edu
                college_degree: Biostatistics
                description: Master of Science
                visibility: true
              - college_logo: umass_seal_1500x1500px.jpg
                college_name: University of Massachusetts Amherst
                college_url: https://umass.edu
                college_degree: Biochemistry & Molecular Biology, Public Health
                description: Bachelor of Science, Bachelor of Science
                visibility: true                

author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: true
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: true

# social links
github_username:  arbogdan
linkedin_username: alexander.r.bogdan
medium_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 1091

# wakatime username (coding activity)
wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: alexander.bogdan.io@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# algolia search
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
 - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
